from .hyperparams import get as H

# THIS FILE IS NOT USED!!!! JUST HERE FOR REFERENCE

PLANNER_PROMPT = (
    (H("PROMPT_PREFIX") or "") +
    "\nYou are analyzing semiconductor datasheet sections to find the most valuable ones for extracting COMPREHENSIVE SCHEMATIC DESIGN rules.\n"
    "Focus on sections that help with PHYSICAL CIRCUIT DESIGN and COMPONENT CONNECTIONS:\n\n"
    "PRIORITY SECTIONS (select these if found):\n"
    "1. \"Electrical Specifications\" or \"DC Characteristics\" - for voltage/current requirements\n"
    "2. \"Absolute Maximum Ratings\" or \"Maximum Ratings\" - for design limits and safety\n"
    "3. \"Power Supply Requirements\" or \"Power Management\" - for supply connections and decoupling\n"
    "4. \"Pin Descriptions\" or \"Pin Functions\" or \"Signal Descriptions\" - for pin connections\n"
    "5. \"Interface Requirements\" or \"Communication Interfaces\" - for interface connections\n"
    "6. \"Layout Recommendations\" or \"PCB Design\" or \"Decoupling\" - for physical layout\n"
    "7. \"Application Information\" or \"Design Guidelines\" - for circuit implementation\n"
    "8. \"Reset Requirements\" - for reset circuit design\n"
    "9. \"Component Requirements\" - for external components (crystals, capacitors, resistors)\n\n"
    "AVOID these sections (not useful for schematic design):\n"
    "- \"Timing Specifications\" or \"AC Characteristics\" or timing-related content\n"
    "- \"Clock Specifications\" or \"Switching Characteristics\" or clock timing\n"
    "- Performance benchmarks or speed specifications\n"
    "- \"Package Information\" or mechanical specs only\n"
    "- \"Ordering Information\"\n\n"
    "Return JSON array of category names for SCHEMATIC DESIGN, keep to 8-15 items.\n"
    "Example: [\"Absolute Maximum Ratings\", \"Electrical Characteristics\", \"Pin Descriptions\", \"Power Supply Requirements\", \"Application Information\", \"Interface Requirements\", \"Layout Guidelines\", \"Component Requirements\", \"Reset Requirements\", \"Analog Specifications\", \"Protection Requirements\"]\n"
)

EXTRACTOR_PROMPT = (
    "You are an expert HARDWARE ENGINEER extracting COMPREHENSIVE, DETERMINISTIC TECHNICAL SPECIFICATIONS for schematic design and PCB implementation.\n\n"
    "SYSTEMATICALLY analyze ALL technical specification sections. For each specification:\n"
    "1. IDENTIFY: Technical parameter, electrical specification, or configuration requirement\n"
    "2. EXTRACT: Exact numerical values, units, tolerances, and conditions\n"
    "3. ASSOCIATE: Specific pins, signals, interfaces, or peripherals affected\n"
    "4. CATEGORIZE: Create specific technical categories based on function\n"
    "5. FORMULATE: Express as precise, actionable engineering specifications\n\n"
    "COMPREHENSIVE TECHNICAL EXTRACTION - INCLUDE ALL, BUT ONLY WHEN EXPLICIT IN EVIDENCE:\n\n"
    "✅ CRITICAL TECHNICAL SPECIFICATIONS TO EXTRACT:\n\n"
    "**1. ELECTRICAL CHARACTERISTICS:**\n"
    "- Exact voltage ranges, current limits, power consumption values\n"
    "- Input/output voltage thresholds (VIH, VIL, VOH, VOL)\n"
    "- Drive strength, slew rate specifications with precise values\n"
    "- ESD protection levels, absolute maximum ratings with exact limits\n\n"
    "**2. REGISTER CONFIGURATION SETTINGS:**\n"
    "- Exact register field values (e.g., PHY_CONFIG_RX_DLL_DELAY_FLD = 0x14)\n"
    "- Control register bit settings for different operating modes\n"
    "- Configuration sequences, initialization procedures with specific steps\n"
    "- Mode-dependent register settings with exact hex values\n\n"
    "**3. PERIPHERAL-SPECIFIC REQUIREMENTS:**\n"
    "- Communication interface specifications (OSPI, SPI, I2C, UART, CAN, etc.)\n"
    "- Analog specifications (ADC/DAC ranges, reference voltages, noise limits)\n"
    "- Clock and PLL configuration requirements with exact frequencies\n"
    "- Memory interface electrical requirements\n\n"
    "**4. COMPONENT VALUES & CONNECTIONS:**\n"
    "- Exact capacitor, resistor, inductor values with tolerances\n"
    "- Crystal specifications (frequency, load capacitance, ESR values)\n"
    "- Decoupling requirements with specific capacitor values per supply pin or rail, quantity per pin/rail, package/voltage rating, and placement constraints (e.g., within 2 mm of pin)\n"
    "- External component requirements with precise specifications\n\n"
    "**5. POWER SUPPLY SPECIFICATIONS:**\n"
    "- Supply voltage ranges with exact min/typ/max values and tolerances\n"
    "- Current consumption specifications for different operating modes\n"
    "- Power supply sequencing requirements with specific timing\n"
    "- Voltage regulator requirements and load regulation specs\n\n"
    "❌ EXCLUDE TIMING SPECIFICATIONS (user doesn't need them):\n"
    "- Setup/hold times, cycle times, pulse durations\n"
    "- Clock frequencies, jitter specifications, duty cycle requirements\n"
    "- Propagation delays, skew limits, transition times\n"
    "- Protocol-specific timing requirements\n\n"
    "**CRITICAL: PIN EXTRACTION REQUIREMENTS:**\n"
    "- ALWAYS include a \"pins\" array with ALL pin names mentioned in the rule\n"
    "- Extract pin names exactly as they appear in the datasheet (e.g., \"OSPI_CLK\", \"VDDA33\", \"PORz\")\n"
    "- For pin ranges like D[7:0], list individual pins: [\"D0\", \"D1\", \"D2\", \"D3\", \"D4\", \"D5\", \"D6\", \"D7\"]\n"
    "- For power/supply rules, include ALL relevant supply pins (e.g., VDDA33, VDDSHV_x pins)\n"
    "- For interface rules, include ALL related signal pins (e.g., SPI_SCLK, SPI_D0, SPI_D1, SPI_CS)\n"
    "- If no specific pins mentioned, leave pins array empty: \"pins\": []\n\n"
    "**CRITICAL: ESSENTIAL CLASSIFICATION REQUIREMENTS:**\n"
    "- ALWAYS include an \"essential\" boolean field for each rule\n"
    "- Set \"essential\": true ONLY for rules that are ABSOLUTELY CRITICAL for basic functionality:\n"
    "  * Power supply voltage ranges and connections (device won't power on without)\n"
    "  * Required external components for operation (crystal, decoupling caps for power)\n"
    "  * Critical pin connections (ground connections, required pull-ups/downs for interfaces)\n"
    "  * Safety-critical requirements (ESD protection, absolute maximum ratings)\n"
    "- Set \"essential\": false for rules that are RECOMMENDED but not strictly required:\n"
    "  * Layout optimization suggestions (noise reduction, trace routing)\n"
    "  * Performance improvements (additional filtering, impedance matching)\n"
    "  * Best practices (component placement, thermal considerations)\n"
    "  * Nice-to-have features (additional decoupling, shielding)\n\n"
    "**CRITICAL: SCHEMATIC VERIFIABILITY REQUIREMENTS:**\n"
    "- ONLY extract rules that are VERIFIABLE by examining:\n"
    "  * The schematic design and netlist\n"
    "  * Component datasheets and application notes\n"
    "  * Pin connections and component values\n"
    "- EXCLUDE rules that require test equipment or environmental testing\n\n"
    "FORMATTING REQUIREMENTS (STRICT):\n"
    "- Each rule must be EXACTLY ONE SENTENCE with complete technical specification\n"
    "- Include ALL numerical values, units, tolerances, and operating conditions\n"
    "- Use specific pin names, signal names, register names as they appear in datasheet\n"
    "- Include exact hex values for register settings (e.g., 0x14, 0x69)\n"
    "- Specify operating modes, voltage levels, frequency ranges where applicable\n"
    "- Focus on PRECISE technical requirements with measurable parameters\n"
    "- FORBIDDEN VAGUE PHRASES: 'per datasheet recommendations', 'as needed', 'as appropriate', 'suitable', 'typical', 'recommended', 'ensure proper', 'adequate', 'minimize', 'keep short', 'nearby', 'close to', 'use pull-ups' without values, or any rule lacking explicit numeric values when such values exist in evidence\n"
    "- If evidence lacks numeric values, you may still include explicit connection/termination rules (e.g., 'Connect JTAG_TMS to GND when not in use', 'Tie XSHUT to VDD with pull-up resistor of 10 kΩ ±1%'); DO NOT invent numbers that aren't present.\n\n"
    "CREATE SPECIFIC CATEGORIES based on actual technical content:\n"
    "- \"Power Supply Requirements\" - voltage ranges, current limits\n"
    "- \"Register Configuration\" - control register settings, initialization values\n"
    "- \"Component Specifications\" - external component values and requirements\n"
    "- \"Interface Requirements\" - communication interface specifications\n"
    "- \"Analog Specifications\" - ADC/DAC ranges, reference requirements\n"
    "- \"Protection Requirements\" - ESD protection, handling requirements\n"
    "- \"Pin Connection Requirements\" - specific pin connections and terminations\n\n"
    "ACCEPTABLE EXAMPLES (GOOD):\n"
    "- 'Place one 100 nF (X7R, 10%, 0402) and one 1 µF (X5R, 10%, 0402) capacitor in parallel between VDDA33 and GND within 2 mm of VDDA33 pin; connect directly to ground plane via one 0.3 mm via.'\n"
    "- 'Tie XSHUT to VDD with 10 kΩ ±1% resistor; add 100 nF to GND at the XSHUT pin.'\n"
    "- 'Use I2C pull-ups: 4.7 kΩ ±5% to VDDIO on SDA and SCL; keep trace length < 50 mm.'\n"
    "UNACCEPTABLE EXAMPLES (BAD):\n"
    "- 'Decouple per datasheet recommendations.' (too vague)\n"
    "- 'Use appropriate pull-ups for I2C.' (no values)\n"
    "- 'Place capacitors near the device.' (no distances/values)\n\n"
    "**The goal is to extract ONLY technical specifications with explicit numeric values that affect hardware design, implementation, or configuration - NO TIMING SPECS.**\n"
)

REWRITER_PROMPT = (
    "Rewrite the following rules into clear, grammatical, standalone English sentences suitable for a schematic checklist.\n"
    "Keep the JSON schema and fields the same (group, rule, pins, essential). Do not add or remove objects; only improve the 'rule' text and normalize 'group' names if obviously synonymous (e.g., Electrical -> Electrical Characteristics).\n"
    "Do NOT invent numbers or facts not present; remove vague filler phrases.\n"
    "Forbidden phrases: 'per datasheet recommendations', 'as needed', 'as appropriate', 'suitable', 'typical', 'ensure proper', 'adequate', 'minimize', 'keep short', 'nearby', 'close to'.\n"
    "If a rule is vague and cannot be made specific without inventing data, keep the exact technical content but eliminate filler words only.\n"
    "Return ONLY a JSON array.\n"
)
